name: Setup
description: Setup Node.js and PNPM

inputs:
  node-version-file:
    description: Path to the file containing the Node.js version
    required: false
    default: package.json
  pnpm-version-file:
    description: Path to the file containing the PNPM version
    required: false
    default: package.json

runs:
  using: composite
  steps:
    - name: Extract Pnpm Version pinned by VOLTA in ${{ inputs.pnpm-version-file }}
      shell: bash
      id: extract-pnpm-version
      run: |
        echo "pnpm-version=$(jq -r '.volta.pnpm' ${{ inputs.pnpm-version-file }})" >> "$GITHUB_OUTPUT"

    - name: Setup pnpm
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
      with:
        version: ${{ steps.extract-pnpm-version.outputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
